#!/usr/bin/env bash
apt-get update
apt-get install -y --no-install-recommends qemu-user-static binfmt-support
apt-get install -y libc6-dev-arm64-cross gcc-aarch64-linux-gnu
update-binfmts --enable qemu-arm
update-binfmts --display qemu-arm
chmod a+x /usr/bin/qemu-*